---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: ${HOMEPAGE_PUID}
      PGID: ${HOMEPAGE_PGID}
    ports:
      - ${HOMEPAGE_PORT}:3000
    volumes:
      - ${HOMEPAGE_CONFIG_PATH}:/app/config # Ensure this directory exists
      - ${HOMEPAGE_IMAGES_PATH}:/app/public/images
      - ${HOMEPAGE_ICONS_PATH}:/app/public/icons
      - ${RAID_MOUNT_PATH}:/RAID
    restart: unless-stopped

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=${DOCKERPROXY_CONTAINERS} # Allow access to viewing containers
      - SERVICES=${DOCKERPROXY_SERVICES} # Allow access to viewing services (for Docker Swarm)
      - TASKS=${DOCKERPROXY_TASKS} # Allow access to viewing tasks (for Docker Swarm)
      - POST=${DOCKERPROXY_POST} # Disallow POST operations (read-only mode)
    ports:
      - ${DOCKERPROXY_PORT_BINDING}:2375
    volumes:
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
