---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${JELLYFIN_PUID}
      - PGID=${JELLYFIN_PGID}
      - TZ=${JELLYFIN_TZ}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    group_add:
      - "${JELLYFIN_GROUP}"
    devices:
      - ${JELLYFIN_DRI_DEVICE}:${JELLYFIN_DRI_DEVICE}
    volumes:
      - ${JELLYFIN_CONFIG_PATH}:/config
      - ${JELLYFIN_TVSHOWS_PATH}:/data/tvshows
      - ${JELLYFIN_MOVIES_PATH}:/data/movies
      - ${JELLYFIN_MUSIC_PATH}:/data/music
      - ${JELLYFIN_BOOKS_PATH}:/data/books
    ports:
      - ${JELLYFIN_PORT}:8096
      - ${JELLYFIN_DISCOVERY_PORT}:7359/udp #optional
      - ${JELLYFIN_DLNA_PORT}:1900/udp #optional
    restart: unless-stopped

  jellyfin-vue:
    image: ghcr.io/jellyfin/jellyfin-vue:unstable
    ports:
      - ${JELLYFIN_VUE_PORT}:80
    environment:
      - DEFAULT_SERVERS=${JELLYFIN_SERVER_IP}:${JELLYFIN_PORT}
      - DISABLE_SERVER_SELECTION=${JELLYFIN_DISABLE_SELECTION}
    restart: unless-stopped
